# Generated by Django 4.1.7 on 2023-04-05 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='email@gmail.com', max_length=200),
        ),
    ]
