# Generated by Django 4.1.7 on 2023-03-30 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Physical_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muscles', models.FloatField()),
                ('fat', models.FloatField()),
                ('body_type', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('weight', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Workout_exercises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.TextField()),
                ('instructions', models.TextField()),
                ('appointment', models.TextField()),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('gif', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Program_workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercises', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.workout_exercises')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
