# Generated by Django 4.1.7 on 2023-04-05 20:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout_program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=100)),
                ('intensity', models.IntegerField(default=100)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('workout_aim', models.CharField(max_length=100)),
                ('sets', models.IntegerField(default=3)),
                ('reps', models.IntegerField(default=8)),
            ],
        ),
        migrations.DeleteModel(
            name='Physical_form',
        ),
        migrations.RemoveField(
            model_name='workout_exercises',
            name='appointment',
        ),
        migrations.RemoveField(
            model_name='workout_exercises',
            name='gif',
        ),
        migrations.AddField(
            model_name='workout_exercises',
            name='intensity',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='workout_exercises',
            name='name',
            field=models.CharField(default='упражнение', max_length=100),
        ),
        migrations.AddField(
            model_name='workout_exercises',
            name='workout_aim',
            field=models.CharField(default='Похудение', max_length=100),
        ),
        migrations.AlterField(
            model_name='workout_exercises',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='exercise_pics'),
        ),
        migrations.DeleteModel(
            name='Program_workout',
        ),
        migrations.AddField(
            model_name='workout_program',
            name='exercises_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.workout_exercises'),
        ),
    ]
