# Generated by Django 4.1.7 on 2023-04-06 07:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_diet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workout', '0002_workout_program_delete_physical_form_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Physical_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('age', models.IntegerField(default=30)),
                ('weight', models.FloatField(default=70)),
                ('intensity', models.IntegerField(default=100)),
                ('workout_aim', models.CharField(default='Похудение', max_length=100)),
                ('muscles', models.FloatField(default=20)),
                ('fat', models.FloatField(default=20)),
                ('body_type', models.TextField(default='Жирный как поезд пассажирный')),
                ('diet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.diet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workout_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.workout_program')),
            ],
        ),
    ]
