# Generated by Django 4.1.7 on 2023-04-06 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0003_physical_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physical_form',
            name='body_type',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='physical_form',
            name='workout_aim',
            field=models.CharField(max_length=100),
        ),
    ]
