# Generated by Django 4.1.7 on 2023-04-06 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0004_alter_physical_form_body_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physical_form',
            name='weight',
            field=models.FloatField(),
        ),
    ]
