# Generated by Django 4.1.7 on 2023-04-06 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0005_alter_physical_form_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physical_form',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='physical_form',
            name='fat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='physical_form',
            name='intensity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='physical_form',
            name='muscles',
            field=models.FloatField(),
        ),
    ]
