# Generated by Django 4.1.7 on 2023-04-06 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0008_alter_workout_program_reps_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout_exercises',
            name='intensity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='workout_exercises',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='workout_exercises',
            name='workout_aim',
            field=models.CharField(max_length=100),
        ),
    ]
