# Generated by Django 4.1.7 on 2023-04-05 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Diet',
        ),
        migrations.RemoveField(
            model_name='food',
            name='image',
        ),
        migrations.RemoveField(
            model_name='food',
            name='title',
        ),
        migrations.AddField(
            model_name='food',
            name='food_image',
            field=models.ImageField(default='default.jpg', upload_to='food_pics'),
        ),
        migrations.AddField(
            model_name='food',
            name='food_name',
            field=models.CharField(default='еда', max_length=100),
        ),
        migrations.AlterField(
            model_name='food',
            name='calories',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='carbohydrates',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='food',
            name='fat',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='glycemic_index',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='proteins',
            field=models.FloatField(default=0),
        ),
    ]
