# Generated by Django 4.1.7 on 2023-04-06 07:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_delete_diet_remove_food_image_remove_food_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diet_name', models.CharField(default='Моя диета', max_length=100)),
                ('schedule', models.DateTimeField(default=django.utils.timezone.now)),
                ('calories', models.FloatField(default=0)),
                ('glycemic_index', models.FloatField(default=0)),
                ('diet_aim', models.CharField(default='Похудение', max_length=100)),
                ('food_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.food')),
            ],
        ),
    ]
