# Generated by Django 4.1.7 on 2023-04-06 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_diet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diet',
            name='calories',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='diet',
            name='diet_aim',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='diet',
            name='diet_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='diet',
            name='glycemic_index',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='food',
            name='calories',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='food',
            name='carbohydrates',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='food',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='food',
            name='fat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='food',
            name='food_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='food',
            name='glycemic_index',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='food',
            name='proteins',
            field=models.FloatField(),
        ),
    ]
